### ISSUE TITLE
Offline messages not working for Mixer announcements

### ISSUE THREAD

**Issue by DelboyDylan** [dawgeth/CouchBot#12]
Since CouchBot's conversion from Beam to Mixer, offline messages have stopped working. Twitch/YT are unaffected.

**Comment by dawgeth** [comment]
This is due to how the Mixer messaging works... it waits to get an offline flag from constellation. If Constellation hiccups, these never get removed. 

I need to write a "heart beat" that will go through and clean up stuff due to Constellation having issues. I will add this to Trello and get working on it ASAP.

**Comment by DelboyDylan** [comment]
FYI, I've performed some tests, and have had reports from other Mixer CouchBot users, and this does unfortunately appear to be a bug within Couchy, rather than Constellation. If it were a hiccup on Constellation's end, I wouldn't expect it to consistently fail to update/delete all Mixer announcements.

I've been running a personal bot on my server alongside CouchBot, and this is receiving the { online: false } notifications from Constellation without issue.
