### ISSUE TITLE
Messages from few streams

### ISSUE THREAD

**Issue by yodek** [dawgeth/CouchBot#9]
Hi!

I can't find command (!cb) which allow me to set that CouchBot will send announce in single message with links no matter how many streams my friend do.

For example my friend use two platforms for streaming: YouTube and Twitch - at this moment CouchBot send two separated message, in first link for Twitch, and about 1 minute later second message with link to YouTube. Why don't write ONE message (anounce) with two links?

**Comment by dawgeth** [comment]
There is currently no method to combine the messages - nor is there a plan to do so in the immediate future. However, I will add a suggestion/feature request on our Trello Board (https://trello.com/b/KisuC9K8/couchbot) for it.

The reasoning is mostly due to the logistics of how everything is checked - everything is on a different time:

Hitbox/Smashcast - 2 minutes
Twitch - 5 minutes
YouTube - 5 minutes
Beam - Instant

--

This would've been more logical when Personal configuration (!cb live) were a thing - as these were linked to a specific Discord User. Now, it just treats everyone in the list (!cb streamer list) as a separate entity. We'd have to also implement a way to link channels across platforms as a "single" streamer. This currently doesn't exist.
